FROM node:22-alpine3.19

# Set the working directory
WORKDIR /app

# Install dependencies only if package.json or package-lock.json changes
COPY package.json package-lock.json ./
RUN --mount=type=cache,target=/app/node_modules \
    npm install

# Copy the rest of the application code
COPY . .

# Expose the application port
EXPOSE 3000

# Start the Next.js application in development mode
CMD ["npm", "run", "dev"]
